name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Command Tests
      run: go test -short -v github.com/davebehr1/spanassessment/cmd/... -count=1

    - name: Package Tests
      run: go test -short -v github.com/davebehr1/spanassessment/pkg/... -count=1

    - name: Acceptance Tests
      run: go test -short -v  github.com/davebehr1/spanassessment/test/acceptance/... -count=1
